CREATE DATABASE IF NOT EXISTS booksDB CHARSET utf8mb4;
USE booksDB;
CREATE TABLE books(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    description TINYTEXT NOT NULL,
    img TINYTEXT NOT NULL,
    author VARCHAR(30) NOT NULL
);